import type { CatalogProduct, FarmInfo, LotInfo } from '../model/types';

// ═══════════════════════════════════════════════════════════════
// MOCK PRODUCTS — migrated from farm_shopping/data/mock.ts
// 🔶 Remove this file when backend API is ready
// ═══════════════════════════════════════════════════════════════

export const mockProducts: CatalogProduct[] = [
  {
    id: 'p1',
    name: 'Cà chua Cherry VietGAP',
    slug: 'ca-chua-cherry-vietgap',
    category: 'Rau củ',
    description: 'Cà chua Cherry trồng trong nhà màng, không sử dụng thuốc trừ sâu hóa học. Vị ngọt thanh, giòn, thích hợp làm salad.',
    shortDescription: 'Cà chua Cherry sạch, an toàn cho sức khỏe.',
    price: 45000,
    unit: 'kg',
    stock: 150,
    images: ['https://picsum.photos/seed/tomato/800/800'],
    sellerId: 'u2',
    farmId: 'f1',
    seasonId: 's1',
    lotId: 'l1',
    region: 'Lâm Đồng',
    traceable: true,
    rating: 4.8,
    reviewCount: 124,
    createdAt: '2024-01-20T10:00:00Z',
    status: 'published',
  },
  {
    id: 'p2',
    name: 'Sầu riêng Ri6',
    slug: 'sau-rieng-ri6',
    category: 'Trái cây',
    description: 'Sầu riêng Ri6 chín cây tự nhiên, cơm vàng hạt lép, thơm ngon đậm đà.',
    shortDescription: 'Sầu riêng Ri6 đặc sản miền Tây.',
    price: 120000,
    unit: 'kg',
    stock: 50,
    images: ['https://picsum.photos/seed/durian/800/800'],
    sellerId: 'u2',
    farmId: 'f2',
    seasonId: 's2',
    lotId: 'l2',
    region: 'Cần Thơ',
    traceable: true,
    rating: 4.9,
    reviewCount: 89,
    createdAt: '2024-05-25T08:00:00Z',
    status: 'published',
  },
  {
    id: 'p3',
    name: 'Xà lách thủy canh',
    slug: 'xa-lach-thuy-canh',
    category: 'Rau củ',
    description: 'Xà lách trồng theo phương pháp thủy canh, sạch 100%, không cần rửa lại trước khi ăn.',
    shortDescription: 'Xà lách thủy canh tươi ngon.',
    price: 35000,
    unit: 'kg',
    stock: 200,
    images: ['https://picsum.photos/seed/lettuce/800/800'],
    sellerId: 'u2',
    farmId: 'f1',
    seasonId: 's1',
    lotId: 'l1',
    region: 'Lâm Đồng',
    traceable: true,
    rating: 4.5,
    reviewCount: 45,
    createdAt: '2024-02-10T09:00:00Z',
    status: 'published',
  },
  {
    id: 'p4',
    name: 'Bưởi da xanh Bến Tre',
    slug: 'buoi-da-xanh-ben-tre',
    category: 'Trái cây',
    description: 'Bưởi da xanh trồng theo phương pháp hữu cơ, vỏ mỏng, tép mọng nước, vị ngọt thanh.',
    shortDescription: 'Bưởi da xanh hữu cơ Bến Tre.',
    price: 55000,
    unit: 'trái',
    stock: 80,
    images: ['https://picsum.photos/seed/pomelo/800/800'],
    sellerId: 'u2',
    farmId: 'f2',
    seasonId: 's2',
    lotId: 'l2',
    region: 'Bến Tre',
    traceable: true,
    rating: 4.7,
    reviewCount: 67,
    createdAt: '2024-03-15T10:00:00Z',
    status: 'published',
  },
  {
    id: 'p5',
    name: 'Nấm đùi gà organic',
    slug: 'nam-dui-ga-organic',
    category: 'Rau củ',
    description: 'Nấm đùi gà trồng trong nhà kính theo tiêu chuẩn organic, thịt nấm chắc, thơm ngon.',
    shortDescription: 'Nấm đùi gà organic tươi.',
    price: 75000,
    unit: 'kg',
    stock: 100,
    images: ['https://picsum.photos/seed/mushroom/800/800'],
    sellerId: 'u2',
    farmId: 'f1',
    seasonId: 's1',
    lotId: 'l1',
    region: 'Lâm Đồng',
    traceable: true,
    rating: 4.6,
    reviewCount: 38,
    createdAt: '2024-04-01T09:00:00Z',
    status: 'published',
  },
  {
    id: 'p6',
    name: 'Mật ong rừng nguyên chất',
    slug: 'mat-ong-rung-nguyen-chat',
    category: 'Đặc sản',
    description: 'Mật ong rừng nguyên chất thu hoạch từ rừng Tây Nguyên, không pha trộn, giữ nguyên hương vị tự nhiên.',
    shortDescription: 'Mật ong rừng Tây Nguyên nguyên chất.',
    price: 250000,
    unit: 'lít',
    stock: 30,
    images: ['https://picsum.photos/seed/honey/800/800'],
    sellerId: 'u2',
    farmId: 'f1',
    seasonId: 's1',
    lotId: 'l1',
    region: 'Đắk Lắk',
    traceable: false,
    rating: 4.9,
    reviewCount: 156,
    createdAt: '2024-02-20T10:00:00Z',
    status: 'published',
  },
];

export const mockFarms: FarmInfo[] = [
  {
    id: 'f1',
    name: 'Nông trại Xanh Đà Lạt',
    region: 'Lâm Đồng',
    address: '123 Đường Hoa, Phường 1, Đà Lạt',
  },
  {
    id: 'f2',
    name: 'Vườn Trái Cây Miền Tây',
    region: 'Cần Thơ',
    address: '456 Đường Sông, Cái Răng, Cần Thơ',
  },
];

export const mockLots: LotInfo[] = [
  { id: 'l1', code: 'LOT-DX23-001', harvestDate: '2024-01-15', seasonName: 'Vụ Đông Xuân 2023' },
  { id: 'l2', code: 'LOT-HT24-001', harvestDate: '2024-05-20', seasonName: 'Vụ Hè Thu 2024' },
];
